version: "3"
services:
  flaskapp:
    container_name: status_flaskapp
    build:
      context: ./flaskapp
      dockerfile: Dockerfile
    volumes:
      - ./flaskapp:/app
    ports:
      - "${FLASKAPP_PORT}:5000"
  cron:
    container_name: status_cron
    restart: always
    stdin_open: true
    tty: true
    build:
      context: cron
      dockerfile: Dockerfile.windows
    volumes:
      - ./cron/crontab.txt:/etc/cron.d/cron-test
    depends_on:
      - flaskapp
