version: "3"
services:
  flaskapp:
    container_name: status_flaskapp
    platform: linux/x86_64
    build:
      context: ./flaskapp
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./flaskapp:/app
    ports:
      - "${FLASKAPP_PORT}:5000"
    environment:
      - DB_URL=${DB_URL}
      - TIMEZONE=${TIMEZONE}
  cron:
    container_name: status_cron
    restart: always
    build:
      context: cron
      dockerfile: Dockerfile
    volumes:
      - ./cron/crontab.txt:/crontab.txt
    depends_on:
      - flaskapp
