services:
  status:
    build:
      context: .
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:5000"
    environment:
      - DB_URL=mysql+pymysql://${DB_USER}:${DB_PASS}@db-status:3306/${DB_NAME}
      - TZ=${TIMEZONE}
      - FLASK_APP=wsgi.py
    depends_on:
      - db-status
    networks:
      - status-orango-network
  db-status:
    restart: always
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - cloudbeaver
      - status-orango-network

networks:
  cloudbeaver:
    external: true
  status-orango-network:
    driver: bridge
    name: status-orango-network