FROM ubuntu:latest

RUN apt-get update && apt-get -y install cron wget

# Copy hello-cron file to the cron.d directory
COPY crontab.txt /etc/cron.d/cron-test
COPY script.sh /script.sh

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/cron-test
RUN chmod +x /script.sh

# Apply cron job
RUN crontab /etc/cron.d/cron-test

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Run the command on container startup
CMD ["cron", "-f"]