"""add description to task

Revision ID: 262737ce338c
Revises: 1ffdf80a17a2
Create Date: 2025-04-29 09:42:39.229233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262737ce338c'
down_revision = '1ffdf80a17a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
